test-generator/Controllers/GenerateController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Generator.Helpers;

using Shared.Models;
using Shared.MockupData;
using Shared.Interfaces;

using Microsoft.AspNetCore.Mvc.Rendering;
using Generator.ViewModels;
using Shared;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Shared.Helpers;

namespace Generator.Controllers
{
    public class GenerateController : Controller
    {
        private readonly ICategoryRepository _categories;
        private readonly IQuestionRepository _questions;
        private readonly IConfiguration _configuration;

        private IExamRepository _exams;

        public GenerateController(ICategoryRepository categories, IQuestionRepository questions, IExamRepository exams, IConfiguration configuration)
        {
            _categories = categories;
            _questions = questions;
            _exams = exams;
            _configuration = configuration;
        }


        public IActionResult Index()
        {
            IEnumerable<ExamModel> exams = _exams.GeneratedExams;
            return View(exams);
        }



        public IActionResult RemoveExam(int? examId)
        {
            if (examId is null)
            {
                return RedirectToAction("Index");
            }

            bool deletionStatus = _exams.DeleteExam(examId.Value);

            return RedirectToAction("Index");
        }





        public IActionResult SetConstraints()
        {
            var viewmodel = new GenerationViewModel()
            {
                // IEnumerable<(CategoryModel cat, bool IsSelected)>, all checboxes initialized to unchecked = false
                CategoriesSelected = _categories.Categories.Select( cat => new CategorySelection() { Category = cat, IsSelected = false } ).ToList(),
            };

            return View(viewmodel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SetConstraints(GenerationViewModel viewmodel)
        {
            if (ModelState.IsValid)
            {
                // TempData["GenerationViewModel"] = viewmodel;
                TempData.Put("GenerationViewModel", viewmodel);
                return RedirectToAction("Confirm");
            }
            else
            {
                return View(viewmodel);
            }


            //HashSet<int> selectedCategoriesIds = null;

            //if (ModelState.IsValid)
            //{
            //    if (viewmodel.Constraints.CategoriesSelected.Count > 0)
            //    {
            //        // ToHashSet to automagically remove duplicates; not sure how selection will be implemented yet
            //        selectedCategoriesIds = viewmodel.Constraints.CategoriesSelected.Select(cat => cat.CategoryId).ToHashSet();
            //    }
            //}
            //else
            //{
            //    // error
            //    return View(viewmodel);
            //}
        }


        public IActionResult Confirm()
        {
            // GenerationViewModel viewmodel = TempData["GenerationViewModel"] as GenerationViewModel;
            GenerationViewModel viewmodel = TempData.Get<GenerationViewModel>("GenerationViewModel");

            if (viewmodel is null)
            {
                return RedirectToAction("SetConstraints");
            }

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Confirm(GenerationViewModel viewmodel)
        {
            IEnumerable<int> catIdsSelected = viewmodel.CategoriesSelected.Where(c => c.IsSelected).Select(c => c.Category.CategoryId);

            GenerationConstraintsModel constraintsFromView = new GenerationConstraintsModel()
            {
                GUID = Guid.NewGuid(),
                ClosedCount = viewmodel.ClosedCount,
                OpenCount = viewmodel.OpenCount,
                CategoryIdsSelected = catIdsSelected.ToHashSet(),
                Title = viewmodel.Title
            };

            ExamMethods examInProgress = ProblemSelector.SelectProblemsForExam(_questions, constraintsFromView);
            int generatedExamId = _exams.StoreExam(examInProgress.SaveData());
            TempData["generatedExamId"] = generatedExamId;

            return RedirectToAction("Summary");
            //_ = Task.Run(() => _emailService.SendEmailAsync(viewmodel.Constraints));


        }

        public IActionResult Summary(int? examId)
        {
            // GenerationViewModel viewmodel = TempData["GenerationViewModel"] as GenerationViewModel;

            int? generatedExamId = TempData["generatedExamId"] as int?;
            if (generatedExamId is null && examId is null)
            {
                return RedirectToAction("SetConstraints");
            }
            // examId from routing is preferred over TempData
            else if (examId is not null)
            {
                generatedExamId = examId;
            }

            ExamModel examInProgress = _exams.RetrieveExam(generatedExamId.Value);
            if (examInProgress is null)
            {
                return RedirectToAction("SetConstraints");
            }

            ExamSummaryViewModel viewmodel = new ExamSummaryViewModel
            {
                ChosenProblemList = _questions.ReadMultipleProblems(examInProgress.ChosenProblemIds).ToList(),
                Exam = examInProgress,
                ExamDbId = generatedExamId.Value
            };

            return View(viewmodel);
        }


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Summary(ExamSummaryViewModel viewmodel)
        //{

        //    return View(viewmodel);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remove(ExamSummaryViewModel viewmodel)
        {
            ExamMethods examMethods = new ExamMethods(_questions);
            examMethods.LoadData(_exams.RetrieveExam(viewmodel.ExamDbId));

            if (0 <= viewmodel.PositionOfProblemToRemove && viewmodel.PositionOfProblemToRemove < examMethods.ChosenProblems.Count)
            {
                examMethods.RemoveProblem(viewmodel.PositionOfProblemToRemove);
            }

            _exams.OverwriteExam(examMethods.SaveData(), viewmodel.ExamDbId);

            return RedirectToAction("Summary", new { examId = viewmodel.ExamDbId });
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(ExamSummaryViewModel viewmodel)
        {
            ExamMethods examMethods = new ExamMethods(_questions);
            examMethods.LoadData(_exams.RetrieveExam(viewmodel.ExamDbId));

            ProblemModel problemToInsert = _questions.ReadProblem(viewmodel.IdOfProblemToInsert);
            if (problemToInsert is not null)
            {
                if (0 <= viewmodel.PositionOfProblemToInsert && viewmodel.PositionOfProblemToInsert < examMethods.ChosenProblems.Count)
                {
                    examMethods.AddProblem(problemToInsert, viewmodel.PositionOfProblemToInsert);
                }
                else
                {
                    examMethods.AddProblem(problemToInsert);
                }
            }

            _exams.OverwriteExam(examMethods.SaveData(), viewmodel.ExamDbId);

            return RedirectToAction("Summary", new { examId = viewmodel.ExamDbId });
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Print(ExamSummaryViewModel viewmodel)
        {

            return RedirectToAction("Print", new { examId = viewmodel.ExamDbId, numberOfStudents = viewmodel.NumberOfStudents });
        }



        public IActionResult Print(int? examId, int? numberOfStudents)
        {
            // GenerationViewModel viewmodel = TempData["GenerationViewModel"] as GenerationViewModel;

            if (numberOfStudents is null || numberOfStudents.Value <= 0)
            {
                numberOfStudents = 1;
            }


            if (examId is null)
            {
                return NotFound();
            }

            ExamModel examToPrint = _exams.RetrieveExam(examId.Value);

            if (examToPrint is null)
            {
                return NotFound();
            }

            ExamPrinter examPrinter = new ExamPrinter(_configuration, _questions);
            examPrinter.LoadExamModel(examToPrint);
            examPrinter.NumberOfStudents = numberOfStudents.Value;

            string rootDirectory = _configuration.GetValue<string>(WebHostDefaults.ContentRootKey);
            string pathToTemplate = Path.Join(rootDirectory, @".\ExamFilesTemplates\Template.tex");
            StreamReader templateFile = new StreamReader(pathToTemplate);

            string timestamp = TimeHelpers.GetTimestamp();
            string sanitizedTitle = StringHelpers.SantizeFileName(examToPrint.Title);
            string pathToOutput = Path.Join(rootDirectory, @$".\ExamFilesOutput\Outputfile-{timestamp}-{sanitizedTitle}.tex");

            // namespace must be explicit, method with name File is also in ContollerBase class!
            System.IO.File.WriteAllBytes(pathToOutput, examPrinter.PrintLatexFile(templateFile).ToArray());

            return Redirect("/Generate/Complete");
        }
    }
}

test-generator/Views/Generate/Confirm.cshtml
@model Generator.ViewModels.GenerationViewModel

@using Shared.Models

@{
    Layout = "_Layout";
}

<form method="post" asp-controller="Generate" asp-action="Confirm">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="ClosedCount"></label>
        <input asp-for="ClosedCount" readonly="@true" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="OpenCount"></label>
        <input asp-for="OpenCount" readonly="@true" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" readonly="@true" class="form-control" />
    </div>


    <div class="form-group">
        <label asp-for="CategoriesSelected">Wybrane kategorie. (Pusty wybór = wszystkie kategorie!)</label>
            <div class="container">
                @for (int i = 0; i < Model.CategoriesSelected.Count(); i++)
                {
                    <div class="col-4 form-check-inline">
                        <input asp-for="@(Model.CategoriesSelected[i].IsSelected)"
                               type="checkbox" disabled="@true"
                               id="@(Model.CategoriesSelected[i].Category.CategoryId)"
                               class="form-check-input">
                        <input asp-for="@(Model.CategoriesSelected[i].IsSelected)" type="hidden" readonly="@true"/>
                        <input asp-for="@(Model.CategoriesSelected[i].Category.CategoryId)" type="hidden" readonly="@true"/>
                        <input asp-for="@(Model.CategoriesSelected[i].Category.CategoryName)" type="hidden" readonly="@true"/>
                        <label for="@(Model.CategoriesSelected[i].Category.CategoryId)"
                               class="form-check-label">
                            @(Model.CategoriesSelected[i].Category.CategoryName)
                        </label>
                    </div>
                }
            </div>
    </div>

    <button type="submit" class="btn btn-success"><i data-feather="check"></i> Dalej</button>
    <component type="typeof(Generator.BlazorComponents.BackButton)" render-mode="Static" />
</form>

test-generator/Views/Generate/Index.cshtml
@model IEnumerable<Shared.Models.ExamModel>

@using Generator.ViewModels

@{
    Layout = "_Layout";
}


<div class="container p-2">
    <div class="row py-2">
        <div class="ml-3 mr-auto">
            <h2>Testy w bazie</h2>
        </div>
    </div>

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th>Tytuł testu</th>
                    <th style="width: 130px">Szczegóły</th> @*Buttons*@
                    <th style="width: 130px">Usuń</th> @*Buttons*@
                </tr>
            </thead>
            <tbody>
                @foreach (ExamModel exam in Model.Reverse())
                {
                    <tr>
                        <td>@exam.Title</td>
                        <td>
                            <a asp-controller="Generate"
                               asp-action="Summary" 
                               asp-route-examId="@exam.DbId" 
                               class="btn btn-primary"> <i data-feather="info"></i> </a>
                        </td>  
                        <td>
                            <a asp-controller="Generate" 
                               asp-action="RemoveExam" 
                               asp-route-examId="@exam.DbId" 
                               class="btn btn-danger"><i data-feather="trash-2"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Brak testów w bazie.</p>
    }
</div>

test-generator/Views/Generate/SetConstraints.cshtml
@model Generator.ViewModels.GenerationViewModel

@using Shared.Models

@{
    Layout = "_Layout";
}

<form method="post" asp-controller="Generate" asp-action="SetConstraints">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="ClosedCount"></label>
        <input asp-for="ClosedCount" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="OpenCount"></label>
        <input asp-for="OpenCount" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
    </div>


    <div class="form-group">
        <label asp-for="CategoriesSelected">Wskaż kategorie. (Pusty wybór = wszystkie kategorie!)</label>
            <div class="container">
                @for (int i = 0; i < Model.CategoriesSelected.Count(); i++)
                {
                    <div class="col-4 form-check-inline">
                        <input asp-for="@(Model.CategoriesSelected[i].IsSelected)"
                               type="checkbox" 
                               id="@(Model.CategoriesSelected[i].Category.CategoryId)"
                               class="form-check-input">
                        <input asp-for="@(Model.CategoriesSelected[i].Category.CategoryId)"  type="hidden"/>
                        <input asp-for="@(Model.CategoriesSelected[i].Category.CategoryName)"  type="hidden"/>
                        <label for="@(Model.CategoriesSelected[i].Category.CategoryId)"
                               class="form-check-label">
                            @(Model.CategoriesSelected[i].Category.CategoryName)
                        </label>
                    </div>
                }
            </div>
    </div>

    <button type="submit" class="btn btn-primary"><i data-feather="arrow-right"></i> Zatwierdź</button>
    <component type="typeof(Generator.BlazorComponents.BackButton)" render-mode="Static" />
</form>

test-generator/Views/Generate/Summary.cshtml
@model Generator.ViewModels.ExamSummaryViewModel

@{
    Layout = "_Layout";
}

<div class="container p-2">
    <div class="row py-2">
        <div class="ml-3 mr-auto">
            <h2>Podsumowanie wybranych zdań</h2>
        </div>
    </div>

    @if (Model.ChosenProblemList.Count > 0)
    {
        <h3><em>@Model.Exam.Title</em></h3>
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
                <tr>
                    <th>Pozycja w teście</th>
                    <th>Id w bazie</th>
                    <th>Typ</th>
                    <th>Treść zadania</th>
                    <th style="width: 130px">Usuń z testu</th> @*Buttons*@
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.ChosenProblemList.Count; i++)
                {
                    <tr>
                        <td>@i</td>
                        <td>@Model.ChosenProblemList[i].IdNumber</td>
                        <td>@Model.ChosenProblemList[i].Type.EnumPrettyLabel()</td>
                        <td>@Model.ChosenProblemList[i].ProblemText.TruncateLongString(100)</td>
                        <td>
                            <form method="post" class="form-inline">
                            <div class="form-group mx-sm-3">
                                <input asp-for="PositionOfProblemToRemove" value="@i" type="hidden" class="form-control">
                                <input asp-for="ExamDbId" type="hidden" readonly="@true" class="form-control">

                                <button asp-controller="Generate" 
                                        asp-action="Remove" 
                                        type="submit" 
                                        class="btn btn-danger" 
                                        data-toggle="tooltip" 
                                        data-placement="top" 
                                        title="Usuń"><i data-feather="trash-2"></i></button>
                            </div>
                            
                            </form>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    }


    <div class="row">
        <div class="ml-auto mr-3 mt-2">
            <p><strong>Ręcznie dodaj zadanie z bazy.</strong></p>

            <form method="post" class="form-inline">
                <input asp-for="ExamDbId" type="hidden" readonly="@true" class="form-control">
                <div class="form-group mx-sm-3">
                    <label asp-for="IdOfProblemToInsert" class="mr-2">Id</label>
                    <input asp-for="IdOfProblemToInsert" class="form-control" placeholder="0">
                </div>
                <div class="form-group mx-sm-3">
                    <label asp-for="PositionOfProblemToInsert" class="mr-2">Pozycja w teście</label>
                    <input asp-for="PositionOfProblemToInsert" class="form-control" placeholder="0">
                </div>
                <button asp-controller="Generate" asp-action="Insert" type="submit" class="btn btn-primary">Dodaj</button>
            </form>
        </div>
    </div>

    <hr />

    <div class="row py-2">
        <div class="col-auto">
            <a asp-controller="Generate" asp-action="Index" class="btn btn-secondary"><i data-feather="arrow-left"></i> Powrót do bazy testów</a>
        </div>
    </div>

    <hr />

    <div class="row py-2 justify-content-between">
        <div class="col-auto mr-auto">
            <a asp-controller="Generate" asp-action="Print" asp-route-examId="@Model.ExamDbId" class="btn btn-success"> <i data-feather="printer"></i> Utwórz jedną grupę</a>
        </div>

        <div class="col-auto ml-auto">
            <form method="post" class="form-inline">
                <input asp-for="ExamDbId" type="hidden" readonly="@true" class="form-control">
                <div class="form-group mx-sm-3">
                    <label asp-for="NumberOfStudents" class="mr-2">Liczba grup</label>
                    <input asp-for="NumberOfStudents" class="form-control" placeholder="0">
                </div>
                <button asp-controller="Generate" asp-action="Print" type="submit" class="btn btn-success"><i data-feather="printer"></i> Utwórz wiele grup</button>
            </form>
        </div>
    </div>
</div>