test-generator/Controllers/ProblemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Generator.Helpers;

using Shared.Models;
using Shared.MockupData;
using Shared.Interfaces;

using Microsoft.AspNetCore.Mvc.Rendering;

using X.PagedList;

namespace Generator.Controllers
{
    public class ProblemController : Controller
    {
        private IQuestionRepository _questions;
        private readonly ICategoryRepository _categories;

        public ProblemController(IQuestionRepository questions, ICategoryRepository categories)
        {
            _questions = questions;
            _categories = categories;
        }

        public IActionResult Index(int? category, int? page)
        {
            IEnumerable<ProblemModel> problems;
            if (category is null || category == 0)
            {
                problems = _questions.Problems;
            }
            else // if (category is not null)
            {
                problems = _questions.Problems.Where(problem => problem.Category.CategoryId == category.Value);
            }

            var CategoriesWithDefault = new List<CategoryModel>()
                { new CategoryModel() { CategoryId = 0, CategoryName = "Wszystkie kategorie" } };
            CategoriesWithDefault.AddRange(_categories.Categories);

            ViewBag.CategoriesWithDefault = CategoriesWithDefault;
            //ViewBag.CategoryDropdownList = new SelectList(CategoriesWithDefault, "CategoryId", "CategoryName",
            //    selectedValue: CategoriesWithDefault.FirstOrDefault(cat => cat.CategoryId == category.Value));

            // Id of current category
            ViewBag.preservedCategory = category;
            ViewBag.preservedPage = page;

            if (category is not null)
            {
                ViewBag.selectedCategoryName = _categories.ReadCategory(category.Value)?.CategoryName ?? String.Empty;
            }

            int pageNumber = page ?? 1;
            return View(problems.ToPagedList(pageNumber, GlobalConstants.PaginationSize));
        }

        public IActionResult Read(int? id, int? category, int? page)
        {
            ViewBag.CategoryList = new SelectList(_categories.Categories, "CategoryId", "CategoryName");

            ViewBag.preservedCategory = category;
            ViewBag.preservedPage = page;

            ProblemModel problem = null;
            if (id is not null)
            {
                problem = _questions.ReadProblem(id.Value);
            }

            if (problem is not null)
            {
                return View(problem);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Update(int id, int? category, int? page)
        {
            var catList = _categories.Categories;
            ViewBag.CategoryList = new SelectList(catList, "CategoryId", "CategoryName");

            ViewBag.preservedCategory = category;
            ViewBag.preservedPage = page;

            var problemToUpdate = _questions.ReadProblem(id);

            return View(problemToUpdate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ProblemModel problem, int? category, int? page)
        {
            var catList = _categories.Categories;
            ViewBag.CategoryList = new SelectList(catList, "CategoryId", "CategoryName");

            if (_categories.ReadCategory(problem.Category.CategoryId) is null)
            {
                ModelState.AddModelError("CustomError", "Kategoria nie jest zdefiniowana w bazie.");
            }

            
            int updateId = problem.IdNumber;

            if (ModelState.IsValid)
            {
                // The form posts only CategoryId, so we read full category object from database
                problem.Category = _categories.ReadCategory(problem.Category.CategoryId);

                _questions.UpdateProblem(updateId, problem);
                return RedirectToAction("Read", new { id = updateId, category = category, page = page });
            }
            else
            {
                // error while updating
                return View(problem);
            }
        }

        public IActionResult Create(int? category, int? page)
        {
            var catList = _categories.Categories;
            ViewBag.CategoryList = new SelectList(catList, "CategoryId", "CategoryName");
            // category is a routing parameter!

            ViewBag.preservedCategory = category;
            ViewBag.preservedPage = page;

            var newProblem = new ProblemModel();

            CategoryModel categoryFromRouting = null;
            if (category is not null && category.Value != 0)
            {
                categoryFromRouting = _categories.ReadCategory(category.Value);
            }
            if (categoryFromRouting is not null)
            {
                newProblem.Category = categoryFromRouting;
            }

            return View(newProblem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProblemModel problem, int? category, int? page)
        {
            var catList = _categories.Categories;
            ViewBag.CategoryList = new SelectList(catList, "CategoryId", "CategoryName");

            if (_categories.ReadCategory(problem.Category.CategoryId) is null)
            {
                ModelState.AddModelError("CustomError", "Kategoria nie jest zdefiniowana w bazie.");
            }

            if (ModelState.IsValid)
            {
                problem.Category = _categories.ReadCategory(problem.Category.CategoryId);

                _ = _questions.CreateProblem(problem);

                return RedirectToAction("Read", new { id = problem.IdNumber, category = category, page = page });
            }
            else
            {
                // error while creating
                return View(problem);
            }
        }

        public IActionResult Delete(int id, int? category, int? page)
        {
            var catList = _categories.Categories;
            ViewBag.CategoryList = new SelectList(catList, "CategoryId", "CategoryName");

            ViewBag.preservedCategory = category;
            ViewBag.preservedPage = page;

            var problemToDelete = _questions.ReadProblem(id);

            return View(problemToDelete);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(ProblemModel problem, int? category, int? page)
        {
            _questions.DeleteProblem(problem.IdNumber);

            return RedirectToAction("Index", new { category = category, page = page });
        }

        //private IActionResult Read(ProblemModel problem)
        //{
        //    return View(problem);
        //}

        //private int? PreserveCategory()
        //{
            // Preserve routing category; 
            //if (this.RouteData.Values["category"] is null)
            //{
            //    return null;
            //}

            // .ToString, in case user manually inputs some garbage
            //bool isParseSuccessful = Int32.TryParse(this.HttpContext.Request.Query["category"].ToString(), out int currentCategory);
            //if (isParseSuccessful)
            //{
            //    return currentCategory;
            //}
            //else
            //{
            //    return null;
            //}
        //}
    }
}

test-generator/Views/Problem/Create.cshtml
@model Shared.Models.ProblemModel

@using Shared.Models

@{
    Layout = "_Layout";
}

<form method="post" asp-controller="Problem" asp-action="Create" asp-route-category="@ViewBag.preservedCategory" asp-route-page="@ViewBag.preservedPage">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="IdNumber"></label>
                <input asp-for="IdNumber" readonly="@true" class="form-control-plaintext" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Score"></label>
                <input asp-for="Score" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Type"></label>
                <select asp-for="Type" class="form-control"
                        asp-items="Html.GetEnumSelectList<ProblemType>()">
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Category.CategoryName"></label>
        <select asp-for="Category.CategoryId" class="form-control"
                asp-items="ViewBag.CategoryList">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="ProblemText"></label>
        <textarea asp-for="ProblemText" class="form-control" rows="15"></textarea>
    </div>

    <button type="submit" class="btn btn-primary"><i data-feather="check"></i> Zatwierdź</button>
    <component type="typeof(Generator.BlazorComponents.BackButton)" render-mode="Static" />
</form>

test-generator/Views/Problem/Delete.cshtml
@model Shared.Models.ProblemModel

@using Shared.Models

@{
    Layout = "_Layout";
}
@*<form method="post">*@
<form method="post" asp-controller="Problem" asp-action="Delete" asp-route-category="@ViewBag.preservedCategory" asp-route-page="@ViewBag.preservedPage">
    @*asp-action="DisplaySummary"*@
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="IdNumber"></label>
                <input asp-for="IdNumber" readonly="@(true)" class="form-control-plaintext" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Score"></label>
                <input asp-for="Score" readonly="@(true)" class="form-control" />
            </div>      
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Type"></label>
                <select asp-for="Type" class="form-control" readonly="@(true)"
                        asp-items="Html.GetEnumSelectList<ProblemType>()">
                    <option readonly selected>@Model.Type.EnumPrettyLabel()</option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Category.CategoryName"></label>
        <select asp-for="Category.CategoryId" class="form-control" readonly="@(true)"
                asp-items="ViewBag.CategoryList">
            <option readonly selected>@Model.Category.CategoryName</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="ProblemText"></label>
        <textarea asp-for="ProblemText" readonly="@(true)" class="form-control" rows="15"></textarea>
    </div>

    <button type="submit" class="btn btn-danger"><i data-feather="trash-2"></i> Usuń</button>
    <component type="typeof(Generator.BlazorComponents.BackButton)" render-mode="Static" />
</form>

test-generator/Views/Problem/Index.cshtml
@model X.PagedList.IPagedList<Shared.Models.ProblemModel>
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

@{
    Layout = "_Layout";
}

<div class="container p-2">
    <div class="row py-2">
        <div class="ml-3 mr-auto">
            <h2>Zadania w bazie</h2>
        </div>

        <div class="ml-auto mr-3">
            <a asp-controller="Problem" asp-action="Create" asp-route-category="@ViewBag.preservedCategory" class="btn btn-primary">
                <i data-feather="file-plus"></i> Nowe zadanie
            </a>
        </div>
    </div>
    <div class="row py-2">
        <div class="ml-3 mr-auto">
            <h3>@ViewBag.selectedCategoryName</h3>
        </div>
        <div class="ml-auto mr-3">
            <div class="dropdown">
                <button class="btn btn-outline-primary dropdown-toggle " type="button" id="categoryDropdown" data-toggle="dropdown">
                    Wybierz kategorię
                </button>

                <div class="dropdown-menu">
                    @foreach (var cat in ViewBag.CategoriesWithDefault)
                    {
                        <a class="dropdown-item" asp-controller="Problem" asp-action="Index" asp-route-category="@cat.CategoryId">@cat.CategoryName</a>
                    }
                </div>
            </div>

            @*@Html.DropDownList("test", (SelectList)ViewBag.CategoryDropdownList, "Wybierz kategorię")*@
        </div>
    </div>

    @if (Model is not null && Model.Count() > 0)
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>@(AttributeGetter.DisplayName<ProblemModel>(nameof(ProblemModel.IdNumber)))</th>
                    <th>@(AttributeGetter.DisplayName<ProblemModel>(nameof(ProblemModel.ProblemText)))</th>
                    <th style="width: 130px"></th> @* Buttons *@
                </tr>
            </thead>
            <tbody>
                @foreach (var problem in Model)
                {
                    <tr>
                        <td>
                            <a asp-controller="Problem" 
                               asp-action="Read" 
                               asp-route-id="@problem.IdNumber" 
                               asp-route-category="@ViewBag.preservedCategory" 
                               class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Szczegóły">
                                @*<i data-feather="file-text"></i>*@ @problem.IdNumber
                            </a>
                        </td>
                        <td>@problem.ProblemText.TruncateLongString(100)</td>
                        <td>
                            <a asp-controller="Problem" 
                               asp-action="Update" 
                               asp-route-id="@problem.IdNumber" 
                               asp-route-category="@ViewBag.preservedCategory" 
                               class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Edytuj">
                                <i data-feather="edit-3"></i>
                            </a>
                            <a asp-controller="Problem" 
                               asp-action="Delete" 
                               asp-route-id="@problem.IdNumber" 
                               asp-route-category="@ViewBag.preservedCategory" 
                               class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Usuń">
                                <i data-feather="trash-2"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            
            @if (ViewBag.preservedCategory is null || ViewBag.preservedCategory == 0)
            {
                <p><i data-feather="alert-triangle"></i> Brak zadań w bazie!</p>
            }
            else
            {
                <p><i data-feather="alert-triangle"></i> Brak zadań w bazie dla wybranej kategorii!</p>
            }
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i data-feather="x"></i></span>
            </button>
        </div>
    }


    @*@Html.PagedListPager(Model, page => Url.Action("Index", new { category = ViewBag.preservedCategory, page }), PagedListRenderOptions.PageNumbersOnly)*@

    @Html.PagedListPager(Model, page => Url.Action("Index", new { category = ViewBag.preservedCategory, page }), new PagedListRenderOptions
        {
            DisplayLinkToIndividualPages = true,
            DisplayPageCountAndCurrentLocation = false,
            MaximumPageNumbersToDisplay = 10,
            LiElementClasses = new string[] { "page-item" },
            PageClasses = new string[] { "page-link" }
        })


</div>

test-generator/Views/Problem/Read.cshtml
@model Shared.Models.ProblemModel

@using Shared.Models 

@{
    Layout = "_Layout";
}
@*<form method="post">*@
<form>
    @*asp-action="DisplaySummary"*@
    <div class="row">
        <div class="col">
            <div class="form-group ">
                <label asp-for="IdNumber"></label>
                <input asp-for="IdNumber" disabled="@(true)" class="form-control-plaintext" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Score"></label>
                <input asp-for="Score" disabled="@(true)" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Type"></label>
                <select asp-for="Type" class="form-control" disabled="@(true)"
                        asp-items="Html.GetEnumSelectList<ProblemType>()">
                    <option disabled selected>@Model.Type.EnumPrettyLabel()</option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Category.CategoryName"></label>
        <select asp-for="Category.CategoryId" class="form-control" disabled="@(true)"
                asp-items="ViewBag.CategoryList">
            <option disabled selected>@Model.Category.CategoryName</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="ProblemText"></label>
        <textarea asp-for="ProblemText" disabled="@(true)" class="form-control" rows="15"></textarea>
    </div>
    @*<button type="submit" class="btn btn-primary">Submit</button>*@
    <a asp-controller="Problem" asp-action="Index" asp-route-category="@ViewBag.preservedCategory" asp-route-page="@ViewBag.preservedPage" class="btn btn-secondary">
        <i data-feather="arrow-left"></i> Wróć do bazy
    </a>
</form>

test-generator/Views/Problem/Update.cshtml
@model Shared.Models.ProblemModel

@using Shared.Models

@{
    Layout = "_Layout";
}

<form method="post" asp-controller="Problem" asp-action="Update" asp-route-category="@ViewBag.preservedCategory" asp-route-page="@ViewBag.preservedPage">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="IdNumber"></label>
                <input asp-for="IdNumber" readonly="@true" class="form-control-plaintext" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Score"></label>
                <input asp-for="Score" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Type"></label>
                <select asp-for="Type" class="form-control"
                        asp-items="Html.GetEnumSelectList<ProblemType>()">
                    <option disabled selected>@Model.Type.EnumPrettyLabel()</option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Category.CategoryName"></label>
        <select asp-for="Category.CategoryId" class="form-control"
                asp-items="ViewBag.CategoryList">
            <option disabled selected>@Model.Category.CategoryName</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="ProblemText"></label>
        <textarea asp-for="ProblemText" class="form-control" rows="15"></textarea>
    </div>
    <button type="submit" class="btn btn-primary"><i data-feather="check"></i> Zatwierdź</button>
    <component type="typeof(Generator.BlazorComponents.BackButton)" render-mode="Static" />
</form>