test-generator/Controllers/FilesController.cs
using Generator.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Shared.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Generator.Controllers
{
    public class FilesController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _rootDirectory;

        public FilesController(IConfiguration config)
        {
            _configuration = config;
            _rootDirectory = _configuration.GetValue<string>(WebHostDefaults.ContentRootKey);
        }

        [Route("Download/{fileName}")]
        public IActionResult Download(string fileName)
        {
            if (fileName == null)
            {
                return NotFound();
            }

            string path = Path.Join(_rootDirectory, @".\ExamFilesOutput\", fileName);
            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return PhysicalFile(path, "application/octet-stream", fileName);
        }

        [Route("Files/")]
        public IActionResult Index()
        {
            string outputDirectory = Path.Join(_rootDirectory, @".\ExamFilesOutput\");
            var filePaths = Directory.EnumerateFiles(outputDirectory).Where(path => path.ToLower().EndsWith(".tex"));

            IEnumerable<FileModel> viewModel = filePaths.Select
            (
                path => new FileModel()
                { 
                    FileName = Path.GetFileName(path), 
                    FreshnessStatus = TimeHelpers.IsFileFresh(System.IO.File.GetCreationTime(path))
                }
            );

            return View(viewModel);
        }
    }
}

test-generator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generator testów</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://code.cdn.mozilla.net/fonts/fira.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/gh/tonsky/FiraCode@5.2/distr/fira_code.css" rel="stylesheet">
    <script src="~/lib/feather-icons/feather.min.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Generator testów</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index"><i data-feather="home"></i> Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Readme"><i data-feather="info"></i> Instrukcja</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Files" asp-action="Index"><i data-feather="download"></i> Pliki do pobrania</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="d-flex justify-content-between">
                <div>2021</div>
                <div><a class="text-primary" href="https://gitlab.com/bltzkrg.22/test-generator" target="_blank" rel="noreferrer">Kod źródłowy <i data-feather="gitlab"></i></a></div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>feather.replace()</script>

    @*The following is required to correctly route to blazor.server.js in a MVC app
    <script src="~/_framework/blazor.server.js" autostart="false"></script>
    <script>
        Blazor.start({
            configureSignalR: function (builder) {
                builder.withUrl("/_blazor");
            }
        });
    </script>*@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>